[telegram_bot]
token = "token"

[telegram_bot.allowed_senders]
[telegram_bot.allowed_senders.alice]
name = "Alice"
id = 12

[telegram_bot.allowed_senders.bob]
name = "Bob"
id = 13

[webcams]


[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"

[queues]
[queues.send_sanpshot_commands]
name = "incoming"

[queues.receive_sanpshot]
name = "outgoing"

[queues.alarmwatcher]
name = "alarmwatcher"

[alarmmanager]
host = "localhost"
port = 3000]
